name: Update from Template

on:
  workflow_dispatch:
  schedule:
    # Запускать каждую неделю в понедельник в 9:00 UTC
    - cron: '0 9 * * 1'

jobs:
  update-from-template:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/GTFB/probo.git || true
    
    - name: Fetch upstream
      run: git fetch upstream
    
    - name: Check for updates
      id: check-updates
      run: |
        if git diff --quiet main upstream/main; then
          echo "no-updates=true" >> $GITHUB_OUTPUT
        else
          echo "no-updates=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create update branch
      if: steps.check-updates.outputs.no-updates == 'false'
      run: |
        git checkout -B update-from-template upstream/main
        git push origin update-from-template --force
    
    - name: Create Pull Request
      if: steps.check-updates.outputs.no-updates == 'false'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "🔄 Update from template"
        body: |
          ## Обновление из шаблона probo
          
          Этот PR содержит обновления из шаблона probo.
          
          ### Изменения:
          - Автоматическое обновление из upstream/main
          - Дата: ${{ github.run_date }}
          
          ### Проверьте:
          - [ ] Все изменения совместимы с текущим проектом
          - [ ] Нет конфликтов с существующим кодом
          - [ ] Тесты проходят успешно
          
          После проверки можно мержить этот PR в main.
        head: update-from-template
        base: main
        delete-branch: false
        draft: false
    
    - name: No updates message
      if: steps.check-updates.outputs.no-updates == 'true'
      run: echo "✅ Нет обновлений из шаблона"
